* Matemática
- [[*Relevamiento del punto de partida][Relevamiento del punto de partida]]

** Relevamiento del punto de partida
Seleccioné este recorte teniendo en cuenta que “la enseñanza de la multiplicación y de la división demanda varios años de trabajo en la escolaridad para que los alumnos puedan identificar los diferentes problemas que esas herramientas permiten resolver, logren dominar la variedad de relaciones numéricas que es posible establecer y elaboren la diversidad de recursos de cálculo que es pertinente disponera propósito de estas operaciones."[fn:1]

Este relevamiento está hecho en base al material de:
- [[http://programaaceleracion.blogspot.com.ar/p/materiales-para-el-docente-y-el-alumno.html?m=1][Programa de Aceleración. C.A.B.A]]
- Hacer matemática 5. Editorial Estrada 
*** Campo Multiplicativo: Completamiento de tablas
1. Los chicos de un grado estaban estudiando sobre el cuerpo humano. Fueron a un quiosco de diarios a comprar revistas para investigar más acerca de este tema. El diariero preparó la siguiente factura. Completá los datos que faltan:

#+begin_html
<table>
<tr>
<th colspan="4" valign="center">Quiosco de diarios y revistas "Enrique" </th>
</tr>

<tr>
<td align="center">Cantidad </td>
<td align="center">Detalle </td>
<td align="center">Precio Unitario </td>
<td align="center">Total por título </td>
</tr>
<tr>
<td align="center">8 </td>
<td align="center">Revistas: El cuidado del Bebe </td>
<td align="center">$3 </td>
<td align="center">............. </td>
</tr>

<tr>
<td align="center" >4 </td>
<td align="center">Revistas: Salud y Deporte </td>
<td align="center">$8 </td>
<td align="center">.............. </td>
</tr>

<tr align="center">
<td>2 </td>
<td>Tu cuerpo (con video) </td>
<td>$7 </td>
<td>.............. </td>
</tr>

<tr align="right">
<td colspan="4">TOTAL............................. </td>

</tr>
</table>
#+end_html

2. Un librero compra lápices en cajas, siempre del mismo tipo, que luego vende sueltos. En la siguiente tabla, figura la cantidad total de lápices que tiene para vender, según las cajas que compre. Completá la tabla

| Cantidad de cajas de lápices | 1 | 2 | 3 |    | 5 |    | 8 | 9 | 10 | 12 | 15 |
| Cantidad de lápices total    | 6 |   |   | 24 |   | 42 |   |   |    |    |    |
*** Juegos en el parque
1. Los chicos de cuarto grado van a un parque. Completá las tablas que aparecen debajo calculando cuánto tienen que pagar en cada uno de los juegos de acuerdo con la cantidad de vueltas que quieran dar:

| Cantidad de vueltas |  1 |  2 | 3 |   4 | 5 | 6 | 7 | 8 | 9 | 10 |
| Vuelta al mundo     | $3 | $6 |   | $12 |   |   |   |   |   |    |



| Cantidad de vueltas | 1 |  2 |   3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| tazas giratorias    |   | $8 | $12 |   |   |   |   |   |   |    |



| Cantidad de vueltas | 1 | 2 |   3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| Autos chocadores    |   |   | $15 |   |   |   |   |   |   |    |



| Cantidad de vueltas |  1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| Montaña Rusa        | $6 |   |   |   |   |   |   |   |   |    |



| Cantidad de vueltas | 1 |   2 | 3 | 4 |   5 | 6 | 7 | 8 | 9 | 10 |
| Cohete espacial     |   | $14 |   |   | $35 |   |   |   |   |    |



| Cantidad de vueltas | 1 | 2 | 3 |   4 | 5 | 6 | 7 | 8 | 9 |  10 |
| Tren Fantasma       |   |   |   | $32 |   |   |   |   |   | $80 |



| Cantidad de vueltas |  1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
| Barquitos           | $9 |   |   |   |   |   |   |   |   |    |



2. ¿Cuáles de los siguientes cálculos pueden servir para averiguar cuánto se gasta en cada juego?
   a) Para 3 vueltas en la montaña rusa:
      6 + 6 + 6 =........   6 – 3 = .......  6 x 3 =........    6 : 3 =........
   b)Para 4 vueltas en el tren fantasma:
     8 + 8 + 8 + 8 =........  8 – 4 =.......  8 x 4 =........  8 : 4 =........
3. ¿Cuáles de las siguientes sumas pueden escribirse como multiplicaciones? En los casos en que se pueda, anoten cuál sería la multiplicación:

a) 5 + 5 + 5 + 5 =

b) 7 + 7 + 7 + 7 + 7 + 7 =

c) 3 + 3 + 4 + 4 =

d) 9 + 9 + 9 =

e) 2 + 2 + 2 + 1 + 7 =

f) 8 + 8 + 8 + 8 + 8 =

g) 6 + 6 + 6 + 6 + 6 + 6 =

h) 3 + 3 + 3 + 3 + 3 + 3 + 3 =

i) 4 + 4 =

j) 12 + 12 + 12 + 12 + 12 =

k) 10 + 10 + 10 + 10 + 10 + 10 =

l) 40 + 40 + 40 =

m) 128 + 128 + 128 =

4. Un cajero automático sólo entrega billetes de $ 10. ¿Cuánto dinero entregó si salieron 3 billetes? ¿Y si salieron 8? 

Completá la siguiente tabla que relaciona la cantidad de billetes de $ 10 que entrega el cajero automático y la correspondiente cantidad de dinero.

| Cantidad de billetes de $10 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 12 | 14 | 15 | 20 |
| Cantidad de dinero          |   |   |   |   |   |   |   |   |   |    |    |    |    |    |
 

*** Tabla para multiplicar
1. Completar cuadro
2. Problemas para revisar lo que hicimos
   1. Marcá el mayor en cada uno de los siguientes pares de productos (sin hacer la cuenta). En cada caso, anotá qué tuviste en cuenta para decidir.
      #+begin_verse
8 x 5             8 x 7
10 x 6            5 x 10
3 x 2             4 x 3
6 x 4             4 x 4
5 x 5             5 x 2
10 x 10           9 x 9
7 x 0             8 x 0
9 x 1             9 x 6
5 x 6             6 x 5
#+end_verse
   2. Escribí los siguientes productos en orden creciente (sin hacer la cuenta):
      #+begin_verse
      6 x 6
      4 x 5
      5 x 5
      9 x 8
      8 x 8
      3 x 5
      6 x 7
      9 x 10
      8 x 7
      #+end_verse
   3. Completá las siguientes tablas
      
      | X | 3 |  4 | 5 | 6 | 7 |
      |---+---+----+---+---+---|
      | 3 |   | 12 |   |   |   |
      | 6 |   | 24 |   |   |   |
      | 9 |   | 45 |   |   |   |

      
      | X | 2 |  8 | 5 | 9 | 4 |
      |---+---+----+---+---+---|
      | 4 |   | 12 |   |   |   |
      | 8 |   | 24 |   |   |   |
      | 9 |   | 45 |   |   |   |
   1. a partir de los resultados ya ubicados, completá la siguiente tabla de multiplicación:

      |  X | 0 | 1 |  2 |  3 |  4 | 5 |  6 |  7 |  8 | 9 | 10 | 11 |
      |  5 | 0 | 5 | 10 | 15 |    |   |    |    |    |   |    |    |
      |  8 |   |   | 16 | 24 | 32 |   |    |    |    |   |    |    |
      | 10 |   |   |    |    |    |   | 60 | 70 | 80 |   |    |    |
   2. Un número multiplicado por 7 da 56. ¿Qué número es?
      Después de buscar el número, identificá entre las siguientes escrituras la (o las) que representan esta adivinanza:
      
      7 + .... = 56   .... x 7 = 56   .... - 7 = 56    7 x .... = 56
   3. Señalá la respuesta correcta:
      - ¿Cuál es el número que, multiplicado por 5, da 40?
        |5|8|10|
      - ¿Cuál es el número que, multiplicado por 7, da 21?
        |6|3|9|
      - ¿Cuál es el número que, multiplicado por 8, da 32?
        |7|3|4|
   4. Inventen adivinanzas similares y desafíen a sus compañeros.
*** Otros problemas (Cuadernillos de capacitación)
1. Un vendedor coloca libros en estantes y quiere que en todos haya la misma cantidad. Tiene 90 libros para 8 estantes. ¿Cuántos podrá poner en cada uno? ¿Le sobran? ¿Cuántos le faltarían para llenar otro estante?
2. En una panadería se preparan 140 facturas por día. Se hornean en bandejas con 8 facturas cada una. ¿Cuántas bandejas se necesitan en total para preparar todas las facturas?
3. Para un festival se necesita ubicar 100 sillas en filas de 12. ¿Cuántas filas podríancompletarse? ¿Cuántas sillas es necesario agregar para que haya en todas la misma cantidad?
4. Para el día del niño se repartieron bolitas entre 4 hermanos. Todos recibieron la misma cantidad. Había 29 bolitas. ¿Cuántas le corresponde a cada uno? ¿Sobraron bolitas?
5. Luego repartieron 29 chocolates para los mismos 4 chicos. ¿Cuántos chocolates le dieron a cada uno? ¿Sobraron chocolates?
6. Hoy es martes, ¿qué día de la semana será dentro de 1000 días?
*** Numeración
1. Contar palabras. Para contar números usamos palabras: Los nombres de los números. Esas palabras ¿son tantas como los números?
   1. ¿Cuántas palabras diferentes se necesitan para contar de 1 a 1.000.000? *Rodea* la respuesta que te parezca
      menos de 100        Entre 100 y 1.000          Un millón.
   2. *Comparen* y *decidan* cuál es la respuesta que consideran más acertada.
   3. *Averigüen* Cuántas palabras diferentes se necesitan para decir los números del 1 hasta el millón y luego *completen*
      Para decir los número hasta un millón hacen falta ............ palabras.
   4. ¿la respuesta de tu equipo fue acertada?
2. Ahora con cifras
   1. ¿Cuántas cifras diferentes se necesitan para escribir todos los números desde el uno hasta el millón?
      1. *Comparen* sus respuesta y *comenten* las diferentes maneras que utilizaron para resolverlo, para estar seguros que no se olvidan de ninguna cifra.
      2. Se necesitan la misma cantidad de cifras para escribir los números hasta un millón que de palabras diferentes para decir esos números?........................
      3. Si un número se escribe con más cifras que otro ¿Se necesitan más palabras diferentes para decirlo? Explicá por qué sí y por qué no. ...............
   2. ¿Cuál de las siguientes es la escritura correcta del número "ciento tres mil quince"? *Rodeala*
      1. 103.150
      2. 130.015
      3. 103.015
      4. 1.003.015
   3. *Elegí* un número de 5 cifras cifras que tenga dos ceros. *Anotalo* y *escribí* cómo se lee. ................
      1. Anoten los números que anotaron sus compañeros de grupo *Compárenlos* y *rodeen* con distintos colores el mayor y el menor de todos ellos.
   4. Escribí con cifras los siguientes números
      1. Tres mil ochocientos veinte:.........
      2. Quinientos mil veinte:........
      3. Ciento cincuenta mil doscientos ocho:.........
   5. Los siguientes números tienen 6 cifras, pero algunas no están escritas. ¿Es posible que alguno sea "ciento cincuenta mil cuatrocientos"? Si es así, *completá* con las cifras que faltan.
      1. 15... ...40
      2. 152 ... ...4
      3. 15... 4 ... ...
      4. 150 ... ... 4
      5. ¿Alguno de estos números puede ser ciento cincuenta mil doscientos cuatro? Si la respuesta es "sí", *rodealo*.
* Footnotes

[fn:1]  Itzcovich, H.,(2007) La Matemática escolar: las prácticas de enseñanza en el aula. Buenos Aires, Aique. En cuadernillo de trabajo de capacitación 2017.
