* Planificación anual
** Horario

| Horario        | Lunes          | Martes        |Miércoles      |Jueves         | Viernes       |
| 1              | P. del Lenguaje| Matemáticas   |C. Sociales    |P. del Lenguaje|P. del lenguaje|
| 2              | Plástica       | Matemáticas   |C. Sociales    |P. del Lenguaje|P. del Lenguaje|
| 3              | Educ. Fisica   |C. Naturales   |Inglés         | Asamblea      |Educ. Física   |
| 4              | Inglés         |C. Naturales   |Inglés         | Música        |C. Sociales    |
| 5              | Matemáticas    |P. del Lenguaje|P. del Lenguaje|Matemáticas    |C. Naturales   |
| 6              | Matemáticas    |P. del Lenguaje|Matemáticas    |Matemáticas    |Matemáticas    |

*Distribución Horaria*

- 23 módulos de 40'
- 8 módulos de Matemática. 3 módulos de 80' y 2 módulos de 40'.
- 8 módulos de Prácticas del lenguaje. 3 módulos de 80' y 2 módulos de 40'.
- 3 de Ciencias Naturales. 1 módulo de 80' y 1 módulo de 40'.
- 3 de Ciencias Sociales. 1 módulo de 80' y 1 módulo de 40'.
- 1 de Asamblea de grado 1 módulo de 40'.

** Prácticas del lenguaje
#+begin_quote 
Para formar practicantes de la lectura y la escritura, es necesario hacer de la escuela una comunidad de lectores y escritores. Una comunidad de lectores que acuden a los textos buscando respuesta para los problemas que necesitan resolver, tratando de encontrar información para comprender mejor algún aspecto del mundo que es objeto de sus preocupaciones, buscando argumentos para defender una posición con la que están comprometidos o para rebatir otra que consideran peligrosa o injusta, deseando conocer otros modos de vida, identificarse con otros autores y personajes o diferenciarse de ellos, correr otras aventuras, enterarse de otras historias, descubrir otras formas de utilizar el lenguaje para crear nuevos sentidos...
Una comunidad de escritores que producen sus propios textos para dar a conocer sus ideas, para informar sobre hechos que los destinatarios necesitan o deben conocer, para incitar a sus lectores a emprender acciones que consideran valiosas, para convencerlos de la validez de los puntos de vista o de las propuestas que intentan promover, para protestar o reclamar, para compartir con los demás una bella frase o un buen escrito, para intrigar o hacer reír...
Hacer de la escuela un ámbito donde lectura y escritura sean prácticas vivas y vitales, donde leer y escribir sean instrumentos poderosos que permitan repensar el mundo y reorganizar el propio pensamiento, donde interpretar y producir textos sean derechos que es legítimo ejercer y responsabilidades que es necesario asumir.

--Diseño Curricular Tomo 2 G.C.A.B.A

#+end_quote


<table>
<tr>
<th colspan="7" align="center"> Primer Cuatrimestre 2017</td>
</th>
<tr>
  <th rowspan="7"> Modalidades Organizativas</th>
  <th rowspan="4" valign="bottom">Situaciones habituales</th>
  <th>Marzo</th>
  <th>Abril</th>
  <th>Mayo</th>
  <th>Junio</th>
  <th>Julio</th>
</tr>
<tr>

  <td rowspan="3" colspan="5">Portfolio de producciones del año <br/> Biblioteca del aula <br/> Asamblea de grado<br/> Biblioteca institucional</td>


</tr>
<tr>
</tr>
<tr>
</tr>
<tr>
  <th rowspan="3"> Secuencias y Proyectos</th>
  <td colspan="2">Antología de cuentos</td>
    <td></td>
    <td colspan="2">Lectura de novela por episodios</td>

</tr>
  <td border="0"></td>
  <td colspan="2">Leer y escribir para estudiar</td>
  <td colspan="2"></td>

<tr>
  <td colspan="2"></td>

  <td colspan="3">Leer en medios digitales</td>
</tr>
</table>

<table>
<tr>
<th colspan="7" align="center"> Segundo Cuatrimestre 2017</td>
</th>
<tr>
  <th rowspan="7"> Modalidades Organizativas</th>
  <th rowspan="4" valign="bottom">Situaciones habituales</th>
  <th>Agosto</th>
  <th>Septiembre</th>
  <th>Octubre</th>
  <th>Noviembre</th>
  <th>Diciembre</th>
</tr>
<tr>

  <td rowspan="3" colspan="5">Portfolio de producciones del año <br/> Biblioteca del aula <br/> Asamblea de grado <br/> Biblioteca institucional</td>


</tr>
<tr>
</tr>
<tr>
</tr>
<tr>
  <th rowspan="3"> Secuencias y Proyectos</th>
  <td colspan="3">Seguir un autor</td>
    <td></td>
  <td></td>
</tr>
  <td border="0"></td>
  <td colspan="2">Leer y escribir para estudiar</td>
  <td colspan="2"></td>

<tr>
  <td colspan="2"></td>

  <td colspan="3">Leer en medios digitales</td>
</tr>
</table>


*** Situaciones habituales

**** Portfolio de producciones
**** Asamblea de grado
**** Biblioteca del aula
*** Secuencias y proyectos
**** Lectura y escritura de relatos tradicionales
**** Leer y escribir para estudiar
**** Leer en medios digitales
*** Situaciones de reflexión sobre el lenguaje
*** Situaciones para valorar y reflexionar sobre los procesos
** Matemáticas
** Ciencias Sociales
** Ciencias Naturales
** Formación ética y ciudadana
