* Planificación anual
** Horario

| Horario | Lunes           | Martes          | Miércoles       | Jueves          | Viernes         |
|       1 | P. del Lenguaje | C. Naturales    | C. Sociales     | P. del Lenguaje | Matemáticas     |
|       2 | P. del Lenguaje | C. Naturales    | C. Sociales     | P. del Lenguaje | Matemáticas     |
|       3 | Educ. Fisica    | Matemáticas     | Inglés          | Asamblea        | Educ. Física    |
|       4 | Plástica        | Inglés          | Inglés          | Música          | C. Sociales     |
|       5 | Matemáticas     | P. del Lenguaje | P. del Lenguaje | Matemáticas     | C. Naturales    |
|       6 | Matemáticas     | P. del Lenguaje | Matemáticas     | Matemáticas     | P. Del Lenguaje |

*Distribución Horaria*

- 23 módulos de 40'
- 8 módulos de Matemática. 3 módulos de 80' y 2 módulos de 40'.
- 8 módulos de Prácticas del lenguaje. 3 módulos de 80' y 2 módulos de 40'.
- 3 de Ciencias Naturales. 1 módulo de 80' y 1 módulo de 40'.
- 3 de Ciencias Sociales. 1 módulo de 80' y 1 módulo de 40'.
- 1 de Asamblea de grado 1 módulo de 40'.

** Prácticas del lenguaje

#+begin_quote 
Para formar practicantes de la lectura y la escritura, es necesario hacer de la escuela una comunidad de lectores y escritores. Una comunidad de lectores que acuden a los textos buscando respuesta para los problemas que necesitan resolver, tratando de encontrar información para comprender mejor algún aspecto del mundo que es objeto de sus preocupaciones, buscando argumentos para defender una posición con la que están comprometidos o para rebatir otra que consideran peligrosa o injusta, deseando conocer otros modos de vida, identificarse con otros autores y personajes o diferenciarse de ellos, correr otras aventuras, enterarse de otras historias, descubrir otras formas de utilizar el lenguaje para crear nuevos sentidos...
Una comunidad de escritores que producen sus propios textos para dar a conocer sus ideas, para informar sobre hechos que los destinatarios necesitan o deben conocer, para incitar a sus lectores a emprender acciones que consideran valiosas, para convencerlos de la validez de los puntos de vista o de las propuestas que intentan promover, para protestar o reclamar, para compartir con los demás una bella frase o un buen escrito, para intrigar o hacer reír...
Hacer de la escuela un ámbito donde lectura y escritura sean prácticas vivas y vitales, donde leer y escribir sean instrumentos poderosos que permitan repensar el mundo y reorganizar el propio pensamiento, donde interpretar y producir textos sean derechos que es legítimo ejercer y responsabilidades que es necesario asumir.

--Diseño Curricular Tomo 2 G.C.A.B.A

#+end_quote
*** Planificación anual
#+begin_html
<table>
<tr>
<th colspan="7" align="center"> Primer Cuatrimestre 2017</td>
</th>
<tr>
  <th rowspan="7"> Modalidades Organizativas</th>
  <th rowspan="4" valign="bottom">Situaciones habituales</th>
  <th>Marzo</th>
  <th>Abril</th>
  <th>Mayo</th>
  <th>Junio</th>
  <th>Julio</th>
</tr>
<tr>

  <td rowspan="3" colspan="5">Portfolio de producciones del año <br/> Biblioteca del aula <br/> Asamblea de grado<br/> Biblioteca institucional</td>


</tr>
<tr>
</tr>
<tr>
</tr>
<tr>
  <th rowspan="3"> Secuencias y Proyectos</th>
  <td colspan="2">Antología de cuentos</td>
    <td></td>
    <td colspan="2">Lectura de novela por episodios</td>

</tr>
  <td border="0"></td>
  <td colspan="2">Leer y escribir para estudiar</td>
  <td colspan="2"></td>

<tr>
  <td colspan="2"></td>

  <td colspan="3">Leer en medios digitales</td>
</tr>
</table>

<table>
<tr>
<th colspan="7" align="center"> Segundo Cuatrimestre 2017</td>
</th>
<tr>
  <th rowspan="7"> Modalidades Organizativas</th>
  <th rowspan="4" valign="bottom">Situaciones habituales</th>
  <th>Agosto</th>
  <th>Septiembre</th>
  <th>Octubre</th>
  <th>Noviembre</th>
  <th>Diciembre</th>
</tr>
<tr>

  <td rowspan="3" colspan="5">Portfolio de producciones del año <br/> Biblioteca del aula <br/> Asamblea de grado <br/> Biblioteca institucional</td>


</tr>
<tr>
</tr>
<tr>
</tr>
<tr>
  <th rowspan="3"> Secuencias y Proyectos</th>
  <td colspan="3">Seguir un autor</td>
    <td></td>
  <td></td>
</tr>
  <td border="0"></td>
  <td colspan="2">Leer y escribir para estudiar</td>
  <td colspan="2"></td>

<tr>
  <td colspan="2"></td>

  <td colspan="3">Leer en medios digitales</td>
</tr>
</table>
#+end_html 
*** Horario
| Hora | Lunes           | Martes   | Miércoles | Jueves   | Viernes   |
|------+-----------------+----------+-----------+----------+-----------|
|    1 | Activ. Habitual |          |           | Proyecto |           |
|    2 | Activ. Habitual |          |           | Proyecto |           |
|    3 |                 |          |           |          |           |
|    4 |                 |          |           |          |           |
|    5 |                 | Proyecto | Reflexión |          |           |
|    6 |                 | Proyecto |           |          | Reflexión |

*** Planificación por proyectos y secuencias
- [[file:pDelLenguageQuintoGrado2017.org][Planificación descriptiva del área de Prácticas del Lenguaje]]
** Matemáticas
*** Tabla de contenidos anuales
#+begin_html
<table>
  <tr>
    <th> </th>
    <th>Primer Bimestre </th>
    <th>Segundo Bimestre </th>
    <th>Tercer Bimestre </th>
    <th>Cuarto Bimestre </th>
  </tr>
  <tr>
    <th>Números y operaciones</th>
    <td>   Lectura, escritura y orden de números hasta 100.00.<br/>
           Resolución de problemas para profundizar el análisis del valor posicional.<br/>
           Descomposiciones aditivas y multiplicativas.<br/>
           Comparación con otros sistemas no posicionales.<br/>
           Cálculos mentales exactos y estimativos con las cuatro operaciones.<br/>
           Resoluciones de problemas de varios pasos y diversos significados y diversos significados de: <strong>suma | resta | multiplicación | división</strong><br/>
           Resolución de problemas que impliquen el análisis del resto.
    </td>
    <td>   Cálculos mentales de mutiplicación y división. Propiedades delas operaciones.<br/>
        Resolución de problemas que impliquen el uso de múltiplos y divisores.<br/>
        Uso de las relaciones del dividendo, divisor, cociente y resto para resolver problemas.
        Resolución de problemas que impliquen el uso del múltiplos y divisores.<br/>
        Definición de múltiplo y divisor de un número. De multiplo común y de divisor común.<br/>
        Resolución de problemas que apelen a diferentes funcionamientos de las fracciones: <strong>repartos, medidas y particiones.</strong><br/>
        Relaciones entre medios cuartos y octavos; tercios, sextos y doceavos; quintos y décimos. </td>
    <td>   Repartos equivalentes y división. Las fracciones para expresar medidas.<br/>
        Fracción de número natural.<br/>
        Comparaciones de fracciones. Cálculo mental de sumas y restas entre fracciones.<br/>
        Expresiones decimales en el <strong>contexto del dinero y la medida</strong>. Equivalencia entre fracciones y decimales. Orden de expresiones fraccionarias y decimales.<br/>
        Recta Numérica.<br/>
        Resolución de problemas que involucren relaciones de proporcionalidad directa.<br/>
        Constante proporcional.<br/>
        Propiedades de las relaciones de proporcionalidad.<br/>
        Elaboración de tablas para organizar datos y favorecer el análisis de los mismos.<br/>
        Resolución de problemas que requieran de la multiplicación o de la división de una fracción o un decimal por un número natural <strong>en contexto de proporcionalidad</strong>.
    </td>
    <td>   Equivalencias entre expresiones fraccionarias y decimales.<br/>
        Utilización de la organización decimal del sistema métrico como contexto para establecer relacones entre fracciones y decimales.<br/>
        Multiplicación y división de un número decimal por la unidad seguida de ceros.<br/>
        Cálculo con expresiones decimales.
    </td>
  </tr>
  <tr>
    <th>Geometría</th>
    <td> </td>
    <td>   Reproducción de figuras con lados rectos y arcos de circunferencia utilizando escuadra, regla y compás.<br/>
            Puntos que cumplen ciertas condiciones. Propiedad de los lados de los triángulos.<br/>
        Propiedad de la suma de los ángulos interiores de los triángulos.<br/>
        Construciones de triángulos con regla, compás y transportador, a partir de diferentes informaciones.
    </td>
    
    <td>   Trazados de rectas perpendiculares con regla y escuadra.<br/>
        Trazados de rectas paralelas con escuadra y regla, con regla y transportador.<br/>
       Construcción de cuadriláteros usando regla, compás y transportador.<br/>
        Clasificación de cuadriláteros según diferentes criterios: <strong>congruencia de lados, tipo de ángulos.</strong><br/>
        Suma de los ángulos interiores de los cuadriláteros.
    </td>
    <td>   Características de cuerpos geométricos: <strong> cantidad y formas de caras, aristas y vértices</strong><br/>
        Características de cuerpos y pirámides. Desarrollo plano de los cuerpos geométricos.
    </td>
  </tr>
  <tr>
    <th>Medida</th>
    <td>Resolución de problemas que impliquen la determinación de duraciones(horas, minutos, segundos).
    </td>
    <td>Uso del transportador para medir y comparar ángulos. Uso del grado como unidad de medida de los ángulos
    </td>
    <td>   Uso de las fracciones para expresar la medida de una superficie considerando otra como unidad.<br/>
        Situaciones de exploración de la independencia de variaciones del área y del perímetro de una figura.
    </td>
    <td>   Equivalencia entre unidades de medida de longitud, peso y capacidad.<br/>
        Uso de expresiones decimáles y fraccionarias para escribir medidas.<br/>
        Estimacioón de medidas.
    </td>
  </tr>
</table>
#+end_html


*** Secuencias
- [[file:mateQuintoGrado2017.org][Planificación descriptiva del área de matemática]]
** Ciencias Sociales
*** Planificación anual
#+BEGIN_HTML
<table>
  <tr>
    <th></th>
    <th>Marzo - Abril - 1/2 Mayo (2 meses)</th>
    <th>1/2 Mayo - Junio - Julio (2 meses)</th>
    <th>Agosto - Septiembre (2 meses)</th>
    <th>Octubre - Noviembre (2 meses)</th>
    <th colspan="2">Diciembre</th>
  </tr
  <tr>
    <th>Bloques</th>
    <th>REVOLUCIONES Y UNIONES Y DESUNIONES 1 (Fines del S XVIII hasta 1820)</th>
    <th>UNIONES Y DESUNIONES 2 (1820 - 1860)</th>
    <th>RECURSOS NATURALES</th>
    <th>CIUDADES</th>
    <th rowspan="2">RECAPITULACIONES Y CIERRES</th>
  </tr>
  <tr>
    <th>Ideas Básicas</th>
    <td>Los cambios producidos en Inglaterra y Francia en las últimas décadas del siglo XVIII modificaron la vida de las personas que habitaban esos países y otras áreas lejanas.
La ruptura del vínculo colonial en Hispanoamérica impulsó la construcción de nuevas sociedades, nuevos territorios y gobiernos, y la transformación de la economía.
El dominio de España por parte de Napoleón y las reacciones en las colonias hispanoamericanas desarticularon el Virreinato del Río de la Plata y afectaron la vida de hombres, mujeres y niños de distintos sectores sociales.
</td>
    <td>En sus intentos por construir un estado centralizado, diferentes grupos sociales y regionales se enfrentaron, debatieron alternativas y lograron acuerdos durante el siglo XIX.</td>
    <td>La valoración y el aprovechamiento de los recursos naturales incide en el asentamiento de la población y en las actividades económicas primarias.
Distintos grupos sociales se apropian, valoran y utilizan los recursos naturales de modo diferente.</td>
    <td>Las ciudades son centros de atracción y concentración de personas, inversiones y productos, y a la vez son centros de difusión de informaciones, decisiones e innovaciones más allá de sus propios límites.
La cantidad de población, las actividades productivas predominantes y la complejidad de los servicios e infraestructura son criterios que permiten diferenciar tipos de ciudades.
</td>
 <td></td>   
  </tr>
  <tr>
    <th>Tema/Recorte</th>
    <td>Impacto de las transformaciones producidas por las Revoluciones Industrial y Francesa en América.
Eje:¿Cómo cambió la vida de los esclavos en la Era de la Revolución? Desde la revolución Francesa a la Revolución de Mayo</td>
    <td>Los caudillos en el marco de las economías provinciales.
Eje: ¿Quiénes eran los caudillos? ¿Por qué se enfrentan las provincias? ¿Cuales son las causas de las luchas entre unitarios y federales?</td>
    <td>(Escala Argentina) Valoración de elementos naturales 1. Recursos mineros (oro, litio), forestales (avance de la frontera agropecuaria bosque chaqueños). suelo (oasis mendocinos), faunísticos (guanacos) 2. El mismo recurso, explotaciones diferentes: Suelo (Actores sociales, Benetton y crianceros). Agua (regadío y electricidad)
Eje:¿De que manera la explotación de determinados recursos incide en el asentamiento y en la organización productiva de las sociedades?</td>
    <td>(escala Argentina) Jerarquía urbana: tipos de ciudades (por cantidad de población, actividades productivas predominantes y complejidad de servicios e infraestructura), grandes, medianas, pequeñas.
La conformación histórica de la ciudad de Buenos Aires.
Eje:¿Cuál es la prestación de servicios que se da en las ciudades, grandes, medianas y pequeñas? ¿Cómo es el acceso a dichos servicios en cada una? ¿Cuáles son sus limitaciones?</td>
<td> </td>
 </tr>
 
</table>
#+END_HTML


