* Planificación anual
** Horario

| Horario | Lunes           | Martes          | Miércoles       | Jueves          | Viernes         |
|       1 | P. del Lenguaje | C. Naturales    | C. Sociales     | P. del Lenguaje | Matemáticas     |
|       2 | P. del Lenguaje | C. Naturales    | C. Sociales     | P. del Lenguaje | Matemáticas     |
|       3 | Educ. Fisica    | Matemáticas     | Inglés          | Asamblea        | Educ. Física    |
|       4 | Plástica        | Inglés          | Inglés          | Música          | C. Sociales     |
|       5 | Matemáticas     | P. del Lenguaje | P. del Lenguaje | Matemáticas     | C. Naturales    |
|       6 | Matemáticas     | P. del Lenguaje | Matemáticas     | Matemáticas     | P. Del Lenguaje |

*Distribución Horaria*

- 23 módulos de 40'
- 8 módulos de Matemática. 3 módulos de 80' y 2 módulos de 40'.
- 8 módulos de Prácticas del lenguaje. 3 módulos de 80' y 2 módulos de 40'.
- 3 de Ciencias Naturales. 1 módulo de 80' y 1 módulo de 40'.
- 3 de Ciencias Sociales. 1 módulo de 80' y 1 módulo de 40'.
- 1 de Asamblea de grado 1 módulo de 40'.

** Prácticas del lenguaje

#+begin_quote 
Para formar practicantes de la lectura y la escritura, es necesario hacer de la escuela una comunidad de lectores y escritores. Una comunidad de lectores que acuden a los textos buscando respuesta para los problemas que necesitan resolver, tratando de encontrar información para comprender mejor algún aspecto del mundo que es objeto de sus preocupaciones, buscando argumentos para defender una posición con la que están comprometidos o para rebatir otra que consideran peligrosa o injusta, deseando conocer otros modos de vida, identificarse con otros autores y personajes o diferenciarse de ellos, correr otras aventuras, enterarse de otras historias, descubrir otras formas de utilizar el lenguaje para crear nuevos sentidos...
Una comunidad de escritores que producen sus propios textos para dar a conocer sus ideas, para informar sobre hechos que los destinatarios necesitan o deben conocer, para incitar a sus lectores a emprender acciones que consideran valiosas, para convencerlos de la validez de los puntos de vista o de las propuestas que intentan promover, para protestar o reclamar, para compartir con los demás una bella frase o un buen escrito, para intrigar o hacer reír...
Hacer de la escuela un ámbito donde lectura y escritura sean prácticas vivas y vitales, donde leer y escribir sean instrumentos poderosos que permitan repensar el mundo y reorganizar el propio pensamiento, donde interpretar y producir textos sean derechos que es legítimo ejercer y responsabilidades que es necesario asumir.

--Diseño Curricular Tomo 2 G.C.A.B.A

#+end_quote
*** Planificación anual
#+begin_html
<table>
<tr>
<th colspan="7" align="center"> Primer Cuatrimestre 2017</td>
</th>
<tr>
  <th rowspan="7"> Modalidades Organizativas</th>
  <th rowspan="4" valign="bottom">Situaciones habituales</th>
  <th>Marzo</th>
  <th>Abril</th>
  <th>Mayo</th>
  <th>Junio</th>
  <th>Julio</th>
</tr>
<tr>

  <td rowspan="3" colspan="5">Portfolio de producciones del año <br/> Biblioteca del aula <br/> Asamblea de grado<br/> Biblioteca institucional</td>


</tr>
<tr>
</tr>
<tr>
</tr>
<tr>
  <th rowspan="3"> Secuencias y Proyectos</th>
  <td colspan="2">Antología de cuentos</td>
    <td></td>
    <td colspan="2">Lectura de novela por episodios</td>

</tr>
  <td border="0"></td>
  <td colspan="2">Leer y escribir para estudiar</td>
  <td colspan="2"></td>

<tr>
  <td colspan="2"></td>

  <td colspan="3">Leer en medios digitales</td>
</tr>
</table>

<table>
<tr>
<th colspan="7" align="center"> Segundo Cuatrimestre 2017</td>
</th>
<tr>
  <th rowspan="7"> Modalidades Organizativas</th>
  <th rowspan="4" valign="bottom">Situaciones habituales</th>
  <th>Agosto</th>
  <th>Septiembre</th>
  <th>Octubre</th>
  <th>Noviembre</th>
  <th>Diciembre</th>
</tr>
<tr>

  <td rowspan="3" colspan="5">Portfolio de producciones del año <br/> Biblioteca del aula <br/> Asamblea de grado <br/> Biblioteca institucional</td>


</tr>
<tr>
</tr>
<tr>
</tr>
<tr>
  <th rowspan="3"> Secuencias y Proyectos</th>
  <td colspan="3">Seguir un autor</td>
    <td></td>
  <td></td>
</tr>
  <td border="0"></td>
  <td colspan="2">Leer y escribir para estudiar</td>
  <td colspan="2"></td>

<tr>
  <td colspan="2"></td>

  <td colspan="3">Leer en medios digitales</td>
</tr>
</table>
#+end_html 
*** Horario
| Hora | Lunes           | Martes   | Miércoles | Jueves   | Viernes   |
|------+-----------------+----------+-----------+----------+-----------|
|    1 | Activ. Habitual |          |           | Proyecto |           |
|    2 | Activ. Habitual |          |           | Proyecto |           |
|    3 |                 |          |           |          |           |
|    4 |                 |          |           |          |           |
|    5 |                 | Proyecto | Reflexión |          |           |
|    6 |                 | Proyecto |           |          | Reflexión |

*** Planificación por proyectos y secuencias
- [[file:pDelLenguageQuintoGrado2017.org][Planificación descriptiva del área de Prácticas del Lenguaje]]
** Matemáticas
*** Tabla de contenidos anuales
#+begin_html
<table>
  <tr>
    <th> </th>
    <th>Primer Bimestre </th>
    <th>Segundo Bimestre </th>
    <th>Tercer Bimestre </th>
    <th>Cuarto Bimestre </th>
  </tr>
  <tr>
    <th>Números y operaciones</th>
    <td>   Lectura, escritura y orden de números hasta 100.00.<br/>
           Resolución de problemas para profundizar el análisis del valor posicional.<br/>
           Descomposiciones aditivas y multiplicativas.<br/>
           Comparación con otros sistemas no posicionales.<br/>
           Cálculos mentales exactos y estimativos con las cuatro operaciones.<br/>
           Resoluciones de problemas de varios pasos y diversos significados y diversos significados de: <strong>suma | resta | multiplicación | división</strong><br/>
           Resolución de problemas que impliquen el análisis del resto.
    </td>
    <td>   Cálculos mentales de mutiplicación y división. Propiedades delas operaciones.<br/>
        Resolución de problemas que impliquen el uso de múltiplos y divisores.<br/>
        Uso de las relaciones del dividendo, divisor, cociente y resto para resolver problemas.
        Resolución de problemas que impliquen el uso del múltiplos y divisores.<br/>
        Definición de múltiplo y divisor de un número. De multiplo común y de divisor común.<br/>
        Resolución de problemas que apelen a diferentes funcionamientos de las fracciones: <strong>repartos, medidas y particiones.</strong><br/>
        Relaciones entre medios cuartos y octavos; tercios, sextos y doceavos; quintos y décimos. </td>
    <td>   Repartos equivalentes y división. Las fracciones para expresar medidas.<br/>
        Fracción de número natural.<br/>
        Comparaciones de fracciones. Cálculo mental de sumas y restas entre fracciones.<br/>
        Expresiones decimales en el <strong>contexto del dinero y la medida</strong>. Equivalencia entre fracciones y decimales. Orden de expresiones fraccionarias y decimales.<br/>
        Recta Numérica.<br/>
        Resolución de problemas que involucren relaciones de proporcionalidad directa.<br/>
        Constante proporcional.<br/>
        Propiedades de las relaciones de proporcionalidad.<br/>
        Elaboración de tablas para organizar datos y favorecer el análisis de los mismos.<br/>
        Resolución de problemas que requieran de la multiplicación o de la división de una fracción o un decimal por un número natural <strong>en contexto de proporcionalidad</strong>.
    </td>
    <td>   Equivalencias entre expresiones fraccionarias y decimales.<br/>
        Utilización de la organización decimal del sistema métrico como contexto para establecer relacones entre fracciones y decimales.<br/>
        Multiplicación y división de un número decimal por la unidad seguida de ceros.<br/>
        Cálculo con expresiones decimales.
    </td>
  </tr>
  <tr>
    <th>Geometría</th>
    <td> </td>
    <td>   Reproducción de figuras con lados rectos y arcos de circunferencia utilizando escuadra, regla y compás.<br/>
    </td>
    <td>   Puntos que cumplen ciertas condiciones. Propiedad de los lados de los triángulos.<br/>
        Propiedad de la suma de los ángulos interiores de los triángulos.<br/>
        Construciones de triángulos con regla, compás y transportador, a partir de diferentes informaciones.
    </td>
    <td>   Trazados de rectas perpendiculares con regla y escuadra.<br/>
        Trazados de rectas paralelas con escuadra y regla, con regla y transportador.<br/>
       Construcción de cuadriláteros usando regla, compás y transportador.<br/>
        Clasificación de cuadriláteros según diferentes criterios: <strong>congruencia de lados, tipo de ángulos.</strong><br/>
        Suma de los ángulos interiores de los cuadriláteros.
    </td>
    <td>   Características de cuerpos geométricos: <strong> cantidad y formas de caras, aristas y vértices</strong><br/>
        Características de cuerpos y pirámides. Desarrollo plano de los cuerpos geométricos.
    </td>
  </tr>
  <tr>
    <th>Medida</th>
    <td>Resolución de problemas que impliquen la determinación de duraciones(horas, minutos, segundos).
    </td>
    <td>Uso del transportador para medir y comparar ángulos. Uso del grado como unidad de medida de los ángulos
    </td>
    <td>   Uso de las fracciones para expresar la medida de una superficie considerando otra como unidad.<br/>
        Situaciones de exploración de la independencia de variaciones del área y del perímetro de una figura.
    </td>
    <td>   Equivalencia entre unidades de medida de longitud, peso y capacidad.<br/>
        Uso de expresiones decimáles y fraccionarias para escribir medidas.<br/>
        Estimacioón de medidas.
    </td>
  </tr>
</table>
#+end_html


*** Secuencias
- [[file:mateQuintoGrado2017.org][Planificación descriptiva del área de matemática]]
** Ciencias Sociales
*** Día de la memoria por la verdad y la justicia
*** 
** Ciencias Naturales
*** Planificación anual
#+begin_html
<table>
 <tr >
  <th colspan="11"><p>Ciencias Naturales</p></th>
 </tr>
 <tr >
  <th ><p>Bloques de contenido</p></th>
  <td ><p>Marzo</p></td>
  <td ><p>Abril</p></td>
  <td ><p>Mayo</p></td>
  <td ><p>Junio</p></td>
  <td ><p>Julio</p></td>
  <td ><p>Agosto</p></td>
  <td ><p>Septiembre</p></td>
  <td ><p>Octubre</p></td>
  <td ><p>Noviembre</p></td>
  <td ><p>Diciembre</p></td>
</tr>
<tr >
 <th rowspan="2"><p>Los materiales</p></td>
 <th > </th>
 <td colspan="2"><p>Los materiales y el calor</p></td>
 <td > </td>
 <td > </td>
 <td > </td>
 <td > </td>
 <td > </td>
 <td > </td>
 <td > </td>
 </tr>
<tr >
 <td > </td>
 <td > </td>
 <td ><p>Los materiales y el sonido</p></td>
 <td > </td>
 <td > </td>
 <td > </td>
 <td > </td>
 <td > </td>
 <td > </td>
 <td > </td>
</tr>
<tr>
 <th  ><p>Los seres vivos</p></th>
 <td  > </td>
 <td  > </td>
 <td  > </td>
 <td colspan="2"><p>Diversidad de los seres vivos/nutrición</p></td>
 <td  > </td>
 <td  > </td>
 <td  > </td>
 <td  > </td>
 <td  > </td>
</tr>
<tr>
 <th  ><p>La tierra y el universo</p></th>
 <td  > </td>
 <td  > </td>
 <td  > </td>
 <td  > </td>
 <td  > </td>
 <td  ><p>La tierra</p></td>
 <td  ><p>El cielo visto desde la tierra</p></td>
 <td  > </td>
 <td  > </td>
 <td  > </td>
</tr>
<tr >
 <th  ><p>El sistema solar</p></th>
 <td  > </td>
 <td  > </td>
 <td  > </td>
 <td  > </td>
 <td  > </td>
 <td  > </td>
 <td  > </td>
 <td  > </td>
 <td colspan="2"><p>El Sistema Solar</p></td>
</tr>
</table>
#+end_html
*** Bloques de contenido. Desglose
- Ejes de análisis
  - Unidad y diversidad;
  - Interacciones, transformaciones y conservación;
  - El hombre y el mundo natural
**** Los materiales
- Los materiales y el calor
  - Los aprendizajes que se proponen permiten interpretar fenómenos, como el equilibrio térmico y los cambios de estado, desde el concepto de transferencia de calor.
  - situaciones cotidianas relacionadas con la transferencia del calor y comparar las apreciaciones subjetivas "caliente o frío" a partir de datos obtenidos mediante el tacto, con mediciones efectuadas con termómetros.
  - realizar mediciones de las variaciones de temperatura de cuerpos en contacto que están inicialmente a diferentes temperaturas, y registrar y analizar los datos de dichas variaciones, considerando la noción de equilibrio térmico.
  - es importante alentarlos a que anticipen posibles resultados de las expe riencias, los pongan a consideración de sus compañeros, intercambien opiniones y argumenten en torno a ellos, antes y después de realizadas.
- Los materiales y el sonido
**** Los seres vivos 
- Diversidad de los seres vivos
- Nutrición
**** La Tierra y el Universo
- La Tierra
- El cielo visto desde la Tierra
**** El sistema solar

** Formación ética y ciudadana
*** Asamblea

